name: "Tag and Release"
on:
  push:
    branches:
      - main

jobs:
  TagAndRelease:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - 
        name: Extract Version
        run: |
          o=$(cat splatnet2statink/splatnet2statink.py | grep "A_VERSION = ")
          a_version=v$(eval echo ${o#"A_VERSION = "})
          echo "::set-output name=A_VERSION::${a_version}"
        id: extract-version
      - 
        name: Git Config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - 
        name: Remove Same Tag If Exists
        run: |
          git tag -d ${{steps.extract-version.outputs.A_VERSION}} || true
          git push --delete origin ${{steps.extract-version.outputs.A_VERSION}} || true
      - 
        name: Push Tag
        run: |
          git tag ${{steps.extract-version.outputs.A_VERSION}}
          git push origin ${{steps.extract-version.outputs.A_VERSION}}
      - 
        name: Install latest gh
        run: |
          sudo apt update
          sudo apt install gh
      - 
        name: Remove Same Release If Exists
        run: |
          gh release delete ${{steps.extract-version.outputs.A_VERSION}} || true
      - 
        name: Create Release
        run: |
          gh release create ${{steps.extract-version.outputs.A_VERSION}} --generate-notes