name: "Auto Releaser"
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - 
        name: Remove Same Release If Exists
        run: |
          gh release delete ${GITHUB_REF##*/} || true
      - 
        name: Create Release
        run: |
          gh release create ${GITHUB_REF##*/} --generate-notes